### PR TITLE
Update dependencies 2024-07

### LINKED ISSUE #362: Fix dependabot security alerts
Ben pointed out that we have 17 security alerts on this repo:
https://github.com/opensafely-core/interactive-templates/security/dependabot  

We should update the affected libraries. I think Dependabot may not be picking up updates to production libraries, only dev ones, so this will need a manual upgrade rather than just merging the existing PRs.

### PR DESCRIPTION
**Pull request by StevenMaude**
This should fix #362, but needs reviewing post-merge to confirm that the security alerts are cleared.

Dependabot fails to generate updates for several dependencies, so let's update everything manually.

### CODE REVIEW

**Comment by StevenMaude** [comment]
This doesn't yet update the test dependencies because that's a little more gnarly:

* The unit tests running in Docker use the OpenSAFELY Docker `latest` image which is actually Python 3.8.
* Even in the OpenSAFELY Docker `v2` image, Python is still only at 3.10 and not the 3.11 that this project uses.
* Updating the Python image version and/or the test dependencies seems to make `test_measures.py` hang or at least very slow. This could also be due to dependencies in the Python image.

**Comment by StevenMaude** [comment]
So I think my questions here reduce down to:

* Since interactive is now in job-server, should we be testing with the same environment as job-server?
* Is it sufficient to test with the same Python version (3.12), or do we need the full set of requirements?

**Comment by StevenMaude** [comment]
Oh, the analysis tests are specifically for actions running with the Python image. But that also begs the question: we have two versions of the Python image; which one should be used, or both?

**Comment by StevenMaude** [comment]
Running locally with the v2 Python image using Python 3.10, this takes much longer to run (more than 10 times longer) and results in:

```
FAILED tests/test_measures.py::test_calculate_total_counts - AssertionError: assert True == 'total'
FAILED tests/test_measures.py::test_calculate_group_counts - AssertionError: assert True == '2022-01-01'
```

**Comment by StevenMaude** [comment]
In conclusion:

* updating the dependencies should be fine
* I'll address the pandas quirkiness in another PR
* we should think about the test strategy, which I'll open an issue for

**Review by iaindillingham — APPROVED** [review]

**Pull request merged**
