### PR TITLE
Test `round_column`

### PR DESCRIPTION
**Pull request by iaindillingham**
In this PR, @LFISHER7, we:

* Add hypothesis as a development dependency 34f707b
* Add the production dependencies that are required by `templates.v2.analysis.measures` 6813da3
* Clarify intent 5f9227e
* Write a generative test for `round_column` 820f5c3
* Fix a bug in `round_column`, which was found by the generative test 7d20b6f

For reference, notes from previous versions of this PR are below.

---

Notice that [the generative test fails][1] when passed this data frame:

```py
data_frame = pandas.DataFrame({"A": 18014398509482627}, index=pandas.Index([0]))
```

Seemingly, `pandas.Series.round` cannot round this very large number. We could change the implementation of `round_column`. However, it's a very large number; far larger than, say, an event count. I'd suggest that we set `max_value` as well as `min_value`, here:

https://github.com/opensafely-core/interactive-templates/blob/820f5c3495b543351435e2e7633b851bb98f7cba/tests/test_measures.py#L16

What do you think? How large a number would we expect to be able to round?

[1]: https://github.com/opensafely-core/interactive-templates/actions/runs/4326069695/jobs/7553037227

---

I'm not sure how best to ensure the analysis package is on the PATH. This approach is explicit and doesn't tinker with Justfile, but I have to placate flake8.

### CODE REVIEW

**Comment by sebbacon** [comment]
I've got totally distracted for weekend "fun" by this interesting bug!

It's a decimals-as-floats precision error -- see the [numpy docs](https://numpy.org/doc/stable/reference/generated/numpy.around.html#numpy.around), specifically that:

> [it] has error due to the inexact representation of decimal fractions in the IEEE floating point standard [[1]](https://numpy.org/doc/stable/reference/generated/numpy.around.html#r907366b089c1-1) and errors introduced when scaling by powers of ten.

The simplest reduction of the problem is

```python
    >>> int(np.rint(18014398509482632/10) * 10)
    18014398509482632
```

An interesting question is "if it's inexact, is it still safe to use?". Or to formulate the question more broadly: given most vectorised operations are going to use floating point arithmetic, are there any scaling or precision errors we would ever care about, and how would we decide that? 

My guess is we'd only care in automatic disclosure control situations, where someone could attack the automatic disclosure software by crafting their inputs such that `int(np.rint((secret_number_to_crack + variable_delta)/10) * 10) == known_unroundable_number`; but for this to be a feasible attack they'd have to a reasonable guess that `secret_number_to_crack` must have a small range of possible values, otherwise their inputs (+ outputs) would have to test a very large number of values of `variable_delta`. 

The next question is: even if it's safe, do we care about efficient vectorised operations in any case? If we don't, we can sacrifice performance for accuracy, by using python's built-in `round(18014398509482632, -1)`, which works. (I'm going to guess this is the correct answer: the performance trade-off is surely not worth the uncertainty; plus I don't think we ever expect huge dataframes to be passing through this function?)

Another interesting question is: if we *did* care about performance, _and_ we didn't care about the fact it's inexact, how would we test it?!

(On an efficiency point, I notice in passing that the rounding function under test uses an inefficient `apply` where it could use a vectorised filter operation)

**Comment by iaindillingham** [comment]
Thanks, @sebbacon. I followed you down the rabbit hole, and spent a useful and interesting hour with Pandas and NumPy 🙂 Could I check my understanding? It is:

> Vectorized operations are fast but inaccurate, because they introduce scaling and precision errors. When might we care about these errors? We might care about these errors when using automatic disclosure control, because they represent an attack vector.

Could you explain the example in more depth?

I agree that the correct answer is to use `round`, because we favour accuracy over speed. If we favoured speed over accuracy, then you asked, "How would we test the implementation?" I'm afraid I don't know, either. Possibly by testing multiple implementations, and checking that the relative execution times remained more-or-less constant over time? Or have I misunderstood your question? 🤔

I didn't want to change the implementation at this stage - the task I set myself was to test the function and then discuss the results with Louis. Nevertheless, I profiled execution time. The alternative implementation modifies the data frame in place, so a comparison with `%timeit` would be unfair: only the first iteration of the loop would be operating on the same data.

```py
from hypothesis.extra.pandas import column, data_frames, range_indexes
s = data_frames([column("A", dtype=int)], index=range_indexes(min_size=1_000_000))

data_frame = s.example()
%time _ = data_frame["A"].apply(lambda x: x if x > 10 else 0)
# CPU times: user 294 ms, sys: 33.7 ms, total: 328 ms
# Wall time: 328 ms

%time _ = data_frame.loc[data_frame["A"] <= 10, "A"] = 0
# CPU times: user 9.3 ms, sys: 2.84 ms, total: 12.1 ms
# Wall time: 10.8 ms
```

Whilst the alternative implementation executes in less time, I concluded that it was too soon to change the implementation. (Louis, I must have made a mistake on Friday, as I came to the opposite conclusion. I shouldn't operate a computer with a heavy cold.)

**Comment by sebbacon** [comment]
>> Vectorized operations are fast but inaccurate, because they introduce scaling and precision errors. When might we care about these errors? We might care about these errors when using automatic disclosure control, because they represent an attack vector.
>
> Could you explain the example in more depth?

Imagine we support automatic output-releasing.  Perhaps we have an action we've controlled and written which does automatic low number suppression on any dataset; and we are confident that "blessed" versions of that action cannot produce identifiably low numbers (and by extension, this would apply to any downstream actions).

Say an attacker wants to work out if Tony Blair has ever had a wart removal procedure. They craft a query along the lines Ben G likes to quote which they expect will identify him and approximately  4 other people.

Given they know that our rounding implementation will not round the number 18014398509482632 (let's call that `known_unroundable_number`), they simply make their study definition add `range(known_unroundable_number-5, known_unroundable_number-5)` to every value in the data frame.  The data frame is automatically released, and they look for the presence of `known_unroundable_number` in the outputs.

What I find really interesting about this bug is that we could _only_ have found it with hypothesis, yet it appears to have quite profound implications for ideas about automated output checking.

> "How would we test the implementation?" ... Or have I misunderstood your question?

I think so, yes. In your test, you test that `result % 10 == 0`. If we wanted to accept that in some cases this were not the case, but that's alright, what test _would_ you write? It's not an important question, just a fun one!

> Whilst the alternative implementation executes in less time, I concluded that it was too soon to change the implementation

Absolutely! I just thought I'd mention it as I noticed it.

**Review by LFISHER7 — APPROVED** [review]
Thanks @iaindillingham , this looks good. Interesting discussion!

**Pull request merged**
